name: Build and Publish NuGet Package

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPOSITORY: ghcr.io/xjonathanlei/strongape

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build NuGet Package
        run: |
          dotnet pack \
            --configuration Release \
            --output ./pack

      - name: Push NuGet Package
        run: |
          dotnet nuget push \
          --source https://api.nuget.org/v3/index.json \
          --api-key "${{ secrets.NUGET_API_KEY }}" \
          ./pack/*
